### ISSUE TITLE
我尝试运行example但是报错。

### ISSUE THREAD

**Issue by arkee11** [qjp88995/qjp-slate-editor#1]
yarn install
yarn build
yarn start
可以启动example中的项目但是直接报错
![image](https://user-images.githubusercontent.com/57891228/82470129-85c37400-9af7-11ea-9038-3e1105d69b94.png)
看起来是build的结果不正确
![image](https://user-images.githubusercontent.com/57891228/82470440-ec489200-9af7-11ea-99c4-2bef6952c63f.png)
请问应该怎么启动这个工程呢？谢谢~

**Comment by arkee11** [comment]
![image](https://user-images.githubusercontent.com/57891228/82471166-e8693f80-9af8-11ea-90e2-30ed2318bef8.png)
补充一张报错处

**Comment by qjp88995** [comment]
在根目录下执行
`yarn install`
`yarn build`
然后切换到example目录执行
`yarn install`
`yarn start`

目前还在开发中，比如操作单元格合并时，选中用的是ctrl+鼠标左键，后续会改进，谢谢关注

**Comment by arkee11** [comment]
> 在根目录下执行
> `yarn install`
> `yarn build`
> 然后切换到example目录执行
> `yarn install`
> `yarn start`
> 
> 目前还在开发中，比如操作单元格合并时，选中用的是ctrl+鼠标左键，后续会改进，谢谢关注


我确实是这样启动的项目，今天我换了另一台电脑尝试依然是同样的错误。
![image](https://user-images.githubusercontent.com/57891228/82517343-72dc8e00-9b4f-11ea-9b15-0aad47221801.png)
我尝试将build后的index.modern.js文件的几个报错处按照源码改了下才能正确打开编辑器页面。
我使用的yarn的最新版@1.22.4。您能尝试下`git clone https://github.com/qjp88995/qjp-slate-editor.git` 重新拉取项目，安装依赖，因为我多次尝试都是一样的结果，若您那边是正常的，麻烦提供一下yarn的版本，我再尝试，谢谢~

**Comment by arkee11** [comment]
![image](https://user-images.githubusercontent.com/57891228/82518621-5a21a780-9b52-11ea-87f0-ba801af95372.png)
我直接将MyEditor.js中对应的函数替换到了build后的index.modern.js中，确实能打开了。但这样只是解决了报错，不是正常build后的文件，所以表格的一切功能都是无法使用的。
![image](https://user-images.githubusercontent.com/57891228/82518969-1c714e80-9b53-11ea-8b93-4aee46a7abb4.png)

**Comment by qjp88995** [comment]
yarn版本
`yarn --version`
`1.22.4`

node版本
`node -v`
`v12.16.12`

哈喽，我是这样启动的
1. 在根目录下执行
`yarn`
`yarn build`
2. 在example执行
`yarn`

发现有报错，转到根目录执行
`yarn start`
新建终端，转到example目录执行
`yarn install`
`yarn start`

**Comment by qjp88995** [comment]
表格功能的使用说明：
当光标不在表格中时，可以使用添加表格
当光标在表格中时，可以进行表格的操作，如何插入行删除行等

**Comment by arkee11** [comment]
> yarn版本
> `yarn --version`
> `1.22.4`
> 
> node版本
> `node -v`
> `v12.16.12`
> 
> 哈喽，我是这样启动的
> 
> 1. 在根目录下执行
>    `yarn`
>    `yarn build`
> 2. 在example执行
>    `yarn`
> 
> 发现有报错，转到根目录执行
> `yarn start`
> 新建终端，转到example目录执行
> `yarn install`
> `yarn start`

这个非常有用，问题解决了，我会关闭这个问题，谢谢~
