### ISSUE TITLE
关于表格选区

### ISSUE THREAD

**Issue by arkee11** [qjp88995/qjp-slate-editor#2]
哈喽，我对你的项目很感兴趣，因为这项工作就是我几个月前做过的，表格这部分困扰了我好久最终才达到了一个不错的效果。这个项目现在表格完成的程度和我当时某个时刻很相似，虽然我们实现的方式不一样，但是表格的思想是可以复用的。
表格的选区和合并从某种角度来说是很相似的，完成了选区合并也很简单。
毋庸置疑，表格最终正确的选区是由起始单元格(鼠标点击的单元格)和选区终止单元格(拖动完抬起的单元格)就可以确定的。
最初我认为由起始单元格和终止单元格组成的矩形就应该是正确的选区
![image](https://user-images.githubusercontent.com/57891228/82570501-41e27480-9bb4-11ea-9a35-8a87a0a7b51e.png)
从这个角度来看，我们获得起点和终点自然可以获得之前包括的单元格，之后给加上颜色选区就完成了。
但是后来我发现选区并没有这么简单，因为我只考虑了根据起点和终点算出一个最大范围就大功告成了，但是有时终点又可以通过其他合并的单元格影响起点
![image](https://user-images.githubusercontent.com/57891228/82571170-275ccb00-9bb5-11ea-80be-255ba30712c4.png)
甚至还有更夸张的
![image](https://user-images.githubusercontent.com/57891228/82571436-891d3500-9bb5-11ea-8ed3-6f2450242563.png)
这种情况整个表格应该全部被选中才对
刚刚算最大范围只是根据起点和终点进行计算，得到了一个变化的位置，还应该根据这个变化的位置为基准进行循环判断，直到这个位置不在变化(原谅我最近比较忙没空仔细研究代码提pr- -)
还有选区的展示，我一开始是用给被选中的单元格加class通过randerelement把class渲染出来完成的，这种选区虽然可行但是毕竟是改slate节点了导致性能极差，肉眼可见的卡顿(我主要用的是removeNode和insertNode可能会打错api名字，记不太清了，每加一个class table都会重新渲染所以很卡)但是让我下定决心重新实现添加class的方式的原因是slate默认的撤销记录的是对slate node 的修改，所以撤销的时候选区又出来了十分崩溃，很显然setNodes这个api也存在这个问题。最后我是操作根据选区操作dom(我的编辑器每个node都有随机的class，insert的时候就已经添加了，所以比较好定位来操作dom添加选区class)。

表格这部分我觉得把整理好的数据json再insert回去比较容易，insertnode的单位可以是table也可以是table-row(数据整理好先remove再insert)。

选区和合并这里，我最终弄了很多辅助数据，就是table、row、cell的slate结构中都有一个data和children并列，里面有{path:{row:0,col:0}来记录每个单元格位置}，有合并的情况就意味着有cell的缺失，这对于计算是很不利的，我把每个因合并而缺少的cell都用一个类似type:tmp-cell的slate元素占位，他也有和其他表格元素一样的data，这样的每一行都是整齐的，对于计算单元格的坐标很方便，计算合并时也有些麻烦，占位的tmp-cell有一些独特的data，像这样data:{path:{row:0,col:0,mergeTop:true,mergeLeft:false}来代表这个占位cell是被哪个方向的单元格合并的来辅助计算。总之表格最复杂的就是选区，有了正确的选区数据合并很简单。

其他的就是合并后单元格内也会将多个空的P保留，还有不知道以后你有没有兴趣支持拖拽改变表格长宽hahahah~

我的实现基本上就是这样，写的比较乱，错别字别太介意，希望能对你有些帮助，也希望你能找到更好的实现方式，加油~

**Comment by arkee11** [comment]
再解释一下那个占位的空cell，它存在于table的slate节点中，结构和cell相似，但是不参与显示只用来辅助计算，renderElement的时候case 'tmp-cell': return null;  希望你能找到更优雅的解决方案ｂ(￣▽￣)ｄ

**Comment by arkee11** [comment]
removeNodes、insertNodes、renderElement打错了好多api啊 T T

**Comment by qjp88995** [comment]
哈哈，目前最新的代码对选区的支持已经比较好了
我的思路是这样的（思路来源于栅格布局）：
1. 统计一个表格共有多少个格子（第一行colSpan的总和）
2. 设置一个变量deposit（沉积物）: number[], 长度为格子数量，比如有一个4*4的表格，初始的deposit=[0, 0, 0, 0]，每个值对应相应的列。比如第一行第一个单元格的rowSpan=2，那么它会占据下一行的位置，那么我们把deposit对应的第一个值设为2-1，当循环到下一行这个位置时，发现有沉积物，则第一个元素向右移动，即offset+1，然后减少对应格子的沉积物。以此类推，代码如下

```javascript
const maxCols = firstRowElement.children.filter(item => item.type === 'table-cell').reduce((total, item) => total + (Number(item.colSpan) || 1), 0);
const deposit = new Array(maxCols).fill(0);
const grids = [];
rows.forEach(([, rowPath]) => {
    const [...cells] = Editor.nodes(editor, {
        at: rowPath,
        match: n => n.type === 'table-cell',
    });
    for (let i = 0, j = 0; i < deposit.length;) {
        if (deposit[i] === 0) {
            if (cells[j]) {
                const [cellElement, cellPath] = cells[j];
                const rowSpan = Number(cellElement.rowSpan || 1);
                const colSpan = Number(cellElement.colSpan || 1);
                grids.push({
                    element: cellElement,
                    path: cellPath,
                    offset: i,
                    row: rowPath[rowPath.length - 1],
                    colSpan,
                    rowSpan,
                });
                j++;
                for (let k = 0; k < colSpan; k++) {
                    deposit[i] = rowSpan - 1;
                    i++;
                }
            } else {
                i++;
            }
        } else {
            deposit[i]--;
            i++;
        }
    }
});
```
3. 统计每个单元格向右偏移的格子数offset，自身的格子数colSpan，所在行row，以及它跨了多少行rowSpan
4. 进行选区。首先找出之前鼠标选区的开始单元格和结束单元格，根据之前统计的单元格的offset、colSpan、row、rowSpan，只要找出比和最小偏移、最大偏移、最小行、最大行内的就好了，代码如下

```javascript
const startGrid = grids.find(item => item.path.toString() === startPath.toString());
const endGrid = grids.find(item => item.path.toString() === endPath.toString());
let minOffset = startGrid.offset > endGrid.offset ? endGrid.offset : startGrid.offset,
    maxOffset = startGrid.offset + startGrid.colSpan > endGrid.offset + endGrid.colSpan ? startGrid.offset + startGrid.colSpan : endGrid.offset + endGrid.colSpan,
    minRow = startGrid.row > endGrid.row ? endGrid.row : startGrid.row,
    maxRow = startGrid.row + startGrid.rowSpan > endGrid.row + endGrid.rowSpan ? startGrid.row + startGrid.rowSpan : endGrid.row + endGrid.rowSpan;
let flag = true, selectedGrids = [];
while (flag && selectedGrids.length < grids.length) {
    const _selectedGrids = grids.filter(item => item.offset >= minOffset && item.offset < maxOffset && item.row >= minRow && item.row < maxRow);
    _selectedGrids.forEach(({ offset, row, colSpan, rowSpan }) => {
        minOffset = minOffset > offset ? offset : minOffset;
        maxOffset = maxOffset > offset + colSpan ? maxOffset : offset + colSpan;
        minRow = minRow > row ? row : minRow;
        maxRow = maxRow > row + rowSpan ? maxRow : row + rowSpan;
    });
    if (_selectedGrids.length === selectedGrids.length) flag = false;
    selectedGrids = _selectedGrids;
}
```

目前在考虑如何在选区的时候不让文字选中，我试了很多办法，比如：
1. 使用css属性: user-select: none, 然而并不生效；
2. 在onMouseMove中使用event.preventDefault()，我想要做到在移动到下一格时阻止默认事件，但事与愿违，一旦开始选择文字，貌似并不能阻止了；
3. 使用slate的Transform中的方法，每次移动都去更改光标，效果不理想
4. 尝试使用onMouseOver去做，或者其他办法

后续的功能中会增加单元格长度的拖拽，当然也会有其他的功能一一开发，才刚起步，路还很长😀

**Comment by qjp88995** [comment]
示例图
![example](https://user-images.githubusercontent.com/21209765/82583626-dacdbb80-9bc5-11ea-873d-19676d8e0e30.gif)

**Comment by arkee11** [comment]
> 示例图
> ![example](https://user-images.githubusercontent.com/21209765/82583626-dacdbb80-9bc5-11ea-873d-19676d8e0e30.gif)

在选区的时候不让文字选中很简单使用window.getSelection().removeAllRanges();
`    const onMouseMove = e => {
        const [cell] = MyEditor.nodes(editor, {
            at: [],
            match: n => n === element,
        });
        if (cell) {
            const [, cellPath] = cell;
            const [table] = MyEditor.nodes(editor, {
                at: cellPath,
                match: n => n.type === 'table',
            });
            if (table) {
                const [tableElement, tablePath] = table;
                const { pathSelection, selectedFlag } = tableElement;
                if (pathSelection && selectedFlag) {
                    if (cellPath.toString() !== pathSelection[1].toString()) {
                        Transforms.setNodes(editor, {
                            pathSelection: [pathSelection[0], cellPath],
                        }, {
                            at: tablePath,
                        });
                    }
                }
            }
            window.getSelection().removeAllRanges();
        }
    }`

**Comment by arkee11** [comment]
> 示例图
> ![example](https://user-images.githubusercontent.com/21209765/82583626-dacdbb80-9bc5-11ea-873d-19676d8e0e30.gif)


使用window.getSelection().removeAllRanges();
```js
    const onMouseMove = e => {
        const [cell] = MyEditor.nodes(editor, {
            at: [],
            match: n => n === element,
        });
        if (cell) {
            const [, cellPath] = cell;
            const [table] = MyEditor.nodes(editor, {
                at: cellPath,
                match: n => n.type === 'table',
            });
            if (table) {
                const [tableElement, tablePath] = table;
                const { pathSelection, selectedFlag } = tableElement;
                if (pathSelection && selectedFlag) {
                    if (cellPath.toString() !== pathSelection[1].toString()) {
                        Transforms.setNodes(editor, {
                            pathSelection: [pathSelection[0], cellPath],
                        }, {
                            at: tablePath,
                        });
                    }
                }
            }
            window.getSelection().removeAllRanges();
        }
    }
```
像是这样

**Comment by arkee11** [comment]
> > 示例图
> > ![example](https://user-images.githubusercontent.com/21209765/82583626-dacdbb80-9bc5-11ea-873d-19676d8e0e30.gif)
> 
> 使用window.getSelection().removeAllRanges();
> 
> ```js
>     const onMouseMove = e => {
>         const [cell] = MyEditor.nodes(editor, {
>             at: [],
>             match: n => n === element,
>         });
>         if (cell) {
>             const [, cellPath] = cell;
>             const [table] = MyEditor.nodes(editor, {
>                 at: cellPath,
>                 match: n => n.type === 'table',
>             });
>             if (table) {
>                 const [tableElement, tablePath] = table;
>                 const { pathSelection, selectedFlag } = tableElement;
>                 if (pathSelection && selectedFlag) {
>                     if (cellPath.toString() !== pathSelection[1].toString()) {
>                         Transforms.setNodes(editor, {
>                             pathSelection: [pathSelection[0], cellPath],
>                         }, {
>                             at: tablePath,
>                         });
>                     }
>                 }
>             }
>             window.getSelection().removeAllRanges();
>         }
>     }
> ```
> 
> 像是这样

![chrome-capture](https://user-images.githubusercontent.com/57891228/82623081-ee9f0f00-9c11-11ea-91e7-8b7772afc3f2.gif)
效果展示

**Comment by arkee11** [comment]
> > 示例图
> > ![example](https://user-images.githubusercontent.com/21209765/82583626-dacdbb80-9bc5-11ea-873d-19676d8e0e30.gif)
> 
> 使用window.getSelection().removeAllRanges();
> 
> ```js
>     const onMouseMove = e => {
>         const [cell] = MyEditor.nodes(editor, {
>             at: [],
>             match: n => n === element,
>         });
>         if (cell) {
>             const [, cellPath] = cell;
>             const [table] = MyEditor.nodes(editor, {
>                 at: cellPath,
>                 match: n => n.type === 'table',
>             });
>             if (table) {
>                 const [tableElement, tablePath] = table;
>                 const { pathSelection, selectedFlag } = tableElement;
>                 if (pathSelection && selectedFlag) {
>                     if (cellPath.toString() !== pathSelection[1].toString()) {
>                         Transforms.setNodes(editor, {
>                             pathSelection: [pathSelection[0], cellPath],
>                         }, {
>                             at: tablePath,
>                         });
>                     }
>                 }
>             }
>             window.getSelection().removeAllRanges();
>         }
>     }
> ```
> 
> 像是这样

这只是个例子，放在这里肯定是不合适的，因为移动会干扰正常的选区，正确的应该是在跨越单元格准备添加样式时添加这行代码，也就是选区行为发生时，类似于这里：
```js
    const isSelected = () => {
        const [cell] = MyEditor.nodes(editor, {
            at: [],
            match: n => n === element,
        });
        if (cell) {
            const [, cellPath] = cell;
            const [table] = MyEditor.nodes(editor, {
                at: cellPath,
                match: n => n.type === 'table',
            });
            if (table) {
                const [tableElement] = table;
                const { pathSelection } = tableElement;
                if (pathSelection && pathSelection[0] && pathSelection[1]) {
                    window.getSelection().removeAllRanges(); //here
                    const selectedCells = MyEditor.getSelectedTableCells(editor, table);
                    return selectedCells.some(([, path]) => path.toString() === cellPath.toString());
                }
            }
        }
        return false;
    }
```
当然我就是举个例子，你肯定能找到更合适的位置

**Comment by arkee11** [comment]
> 哈哈，目前最新的代码对选区的支持已经比较好了
> 我的思路是这样的（思路来源于栅格布局）：
> 
> 1. 统计一个表格共有多少个格子（第一行colSpan的总和）
> 2. 设置一个变量deposit（沉积物）: number[], 长度为格子数量，比如有一个4*4的表格，初始的deposit=[0, 0, 0, 0]，每个值对应相应的列。比如第一行第一个单元格的rowSpan=2，那么它会占据下一行的位置，那么我们把deposit对应的第一个值设为2-1，当循环到下一行这个位置时，发现有沉积物，则第一个元素向右移动，即offset+1，然后减少对应格子的沉积物。以此类推，代码如下
> 
> ```js
> const maxCols = firstRowElement.children.filter(item => item.type === 'table-cell').reduce((total, item) => total + (Number(item.colSpan) || 1), 0);
> const deposit = new Array(maxCols).fill(0);
> const grids = [];
> rows.forEach(([, rowPath]) => {
>     const [...cells] = Editor.nodes(editor, {
>         at: rowPath,
>         match: n => n.type === 'table-cell',
>     });
>     for (let i = 0, j = 0; i < deposit.length;) {
>         if (deposit[i] === 0) {
>             if (cells[j]) {
>                 const [cellElement, cellPath] = cells[j];
>                 const rowSpan = Number(cellElement.rowSpan || 1);
>                 const colSpan = Number(cellElement.colSpan || 1);
>                 grids.push({
>                     element: cellElement,
>                     path: cellPath,
>                     offset: i,
>                     row: rowPath[rowPath.length - 1],
>                     colSpan,
>                     rowSpan,
>                 });
>                 j++;
>                 for (let k = 0; k < colSpan; k++) {
>                     deposit[i] = rowSpan - 1;
>                     i++;
>                 }
>             } else {
>                 i++;
>             }
>         } else {
>             deposit[i]--;
>             i++;
>         }
>     }
> });
> ```
> 
> 1. 统计每个单元格向右偏移的格子数offset，自身的格子数colSpan，所在行row，以及它跨了多少行rowSpan
> 2. 进行选区。首先找出之前鼠标选区的开始单元格和结束单元格，根据之前统计的单元格的offset、colSpan、row、rowSpan，只要找出比和最小偏移、最大偏移、最小行、最大行内的就好了，代码如下
> 
> ```js
> const startGrid = grids.find(item => item.path.toString() === startPath.toString());
> const endGrid = grids.find(item => item.path.toString() === endPath.toString());
> let minOffset = startGrid.offset > endGrid.offset ? endGrid.offset : startGrid.offset,
>     maxOffset = startGrid.offset + startGrid.colSpan > endGrid.offset + endGrid.colSpan ? startGrid.offset + startGrid.colSpan : endGrid.offset + endGrid.colSpan,
>     minRow = startGrid.row > endGrid.row ? endGrid.row : startGrid.row,
>     maxRow = startGrid.row + startGrid.rowSpan > endGrid.row + endGrid.rowSpan ? startGrid.row + startGrid.rowSpan : endGrid.row + endGrid.rowSpan;
> let flag = true, selectedGrids = [];
> while (flag && selectedGrids.length < grids.length) {
>     const _selectedGrids = grids.filter(item => item.offset >= minOffset && item.offset < maxOffset && item.row >= minRow && item.row < maxRow);
>     _selectedGrids.forEach(({ offset, row, colSpan, rowSpan }) => {
>         minOffset = minOffset > offset ? offset : minOffset;
>         maxOffset = maxOffset > offset + colSpan ? maxOffset : offset + colSpan;
>         minRow = minRow > row ? row : minRow;
>         maxRow = maxRow > row + rowSpan ? maxRow : row + rowSpan;
>     });
>     if (_selectedGrids.length === selectedGrids.length) flag = false;
>     selectedGrids = _selectedGrids;
> }
> ```
> 
> 目前在考虑如何在选区的时候不让文字选中，我试了很多办法，比如：
> 
> 1. 使用css属性: user-select: none, 然而并不生效；
> 2. 在onMouseMove中使用event.preventDefault()，我想要做到在移动到下一格时阻止默认事件，但事与愿违，一旦开始选择文字，貌似并不能阻止了；
> 3. 使用slate的Transform中的方法，每次移动都去更改光标，效果不理想
> 4. 尝试使用onMouseOver去做，或者其他办法
> 
> 后续的功能中会增加单元格长度的拖拽，当然也会有其他的功能一一开发，才刚起步，路还很长😀

我尝试理解了一下你的方案，貌似并没有解决这种复杂选区的情况，有时选区比较复杂计算出的最小偏移、最大偏移、最小行、最大行会重新导致选区的变化
![chrome-capture1](https://user-images.githubusercontent.com/57891228/82624450-32474800-9c15-11ea-8ddb-cb7db103bb86.gif)
像是这种，单次计算得到的数据不能满足要求。

**Comment by qjp88995** [comment]
是的，当上方单元格横跨多行这种情况没有考虑到，我需要再重新修改一下
`window.getSelection().removeAllRanges()`
这个很有用

**Comment by arkee11** [comment]
> 是的，当上方单元格横跨多行这种情况没有考虑到，我需要再重新修改一下
> `window.getSelection().removeAllRanges()`
> 这个很有用

![chrome-capture (1)](https://user-images.githubusercontent.com/57891228/82625811-b2bb7800-9c18-11ea-9702-ab02a4b52864.gif)
表格的情况太多了，一定要找到通用的方法适用于各种情况，这是我之前完成的表格选区，基本上最复杂的就是这种了，你可以合并出一个类似的测试下。
还有现在ctrl+z撤销会将选区撤销出来也是要考虑的，我当初就是因为这个不得已才去直接操作dom添加选区样式。

**Comment by qjp88995** [comment]
是的，你说的这个问题还是蛮重要的，选区完后，按ctrl+z后鼠标移动会重新触发选区，我会考虑改进的
